language: csharp
sudo: required
dist: trusty

before_install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list' 
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get -y install dotnet-dev-1.0.0-preview2-003118
  - sudo apt-get install dotnet-sharedframework-microsoft.netcore.app-1.0.0-rc2-3002702
  - dotnet --info

install:
  - dotnet restore
  - dotnet build src/PaulMiami.AspNetCore.Mvc.Recaptcha/project.json

script:
  - dotnet test test/PaulMiami.AspNetCore.Mvc.Recaptcha.Test/project.json